/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bgAmber: '#ffbf00',
        white: '#FFFFFF',
        dark: '#03314B',
        success: '#82D616',
        black: '#353935',
        border: '#E2E8F0',
        placeholder: '#64748B',
        gray: 'gray',
        lightgray: 'lightgray',
        cprimaryLight: '#f66',
        cprimaryDark: '#E96E6E',
        cblue: '#4267B2',
        cred: '#EA4335',
        cinputBg: '#E2E8F0',
        cinputCol: '#C0C0C0',
        botLinearOne: '#FDF0F3',
        botLinearTwo: '#FFFBFC',
        lightgreen: '#2ecc71',
        catBgColor: '#DFDCDC',
        catColor: '#938F8F',
        productTitle: '#444444',
        productPrice: '#9C9C9C',
        sizeActive: '#E55B5B',
        ringOne: '#ee8c8c',
        ringTwo: '#f6c5c5',
        cartText: '#757575',
        toastSuccess: '#2ecc71',
        toastDanger: '#e74c3c',
        toastInfo: '#3498db',
        toastWarning: '#f39c12',
        razorPayTheme: '#F37254',
      },
    },
  },
  plugins: [],
};
